import type { Metadata } from "next";
import { GeistSans } from "geist/font";
import "./globals.css";

import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} max-w-screen-xl px-6 2xl:px-0 mx-auto bg-white text-secondary-100`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
